name: Martin Test
favicon: null
layout_spectrum: 0.5311328454408795
typography_spectrum: 0.36914112349040806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.45474127936176956
  lightness: 0.3325542719103396
  saturation: 0.8138306688051671
  rhythmicContrast: 0.16288830968551338
purpose: []
